on:
  push: # 検証時にmainにpush時に実行されたほうが繰り返しやすいため設定
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # ツールによってチャートのパスを明示する必要があるためリストアップしておく
        chart:
          - mywebapp
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0

      - name: Set up helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

      - name: Install kubeconform
        run: |
          wget -q -O - https://github.com/yannh/kubeconform/releases/download/v0.6.6/kubeconform-linux-amd64.tar.gz | tar -zxvf - -C /usr/local/bin

      - name: Install Polaris
        run: |
          wget -q -O - https://github.com/FairwindsOps/polaris/releases/download/9.2.0/polaris_linux_amd64.tar.gz | tar -zxvf - -C /usr/local/bin

      - name: Install Pluto
        run: |
          wget -q -O - https://github.com/FairwindsOps/pluto/releases/download/v5.19.4/pluto_5.19.4_linux_amd64.tar.gz | tar -zxvf - -C /usr/local/bin

      - name: "[${{ matrix.chart }}]: Lint Helm Chart"
        run: helm lint ./charts/${{ matrix.chart }}
        continue-on-error: true
        id: helm_lint

      - name: "[${{ matrix.chart }}]: Run kubeconform"
        run: kubeconform --summary -output json ./charts/${{ matrix.chart }}
        continue-on-error: true
        id: kubeconform

      - name: "[${{ matrix.chart }}]: Run Polaris audit"
        run: polaris audit --only-show-failed-tests --helm-chart ./charts/${{ matrix.chart }}
        continue-on-error: true
        id: polaris

      - name: "[${{ matrix.chart }}]: Run Pluto"
        run: pluto detect-files -d ./charts/${{ matrix.chart }}
        continue-on-error: true
        id: pluto

      - name: "[${{ matrix.chart }}]: Run Trivy vulnerability scanner in IaC mode"
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # tag=0.24.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          scan-ref: 'charts/${{ matrix.chart }}'
          # output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
        id: trivy

      - name: Check results
        run: |
          if [ ${{ steps.helm_lint.outcome }} == 'failure' ] || [ ${{ steps.kubeconform.outcome }} == 'failure' ] || [ ${{ steps.pluto.outcome }} == 'failure' ] || [ ${{ steps.polaris.outcome }} == 'failure' || [ ${{ steps.trivy.outcome }} == 'failure' ] ]; then
            echo "One or more steps failed"
            exit 1
          else
            echo "All steps succeeded"
            exit 0
          fi